name: Test Application

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y arp-scan
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
    
    - name: Run syntax check
      run: |
        python -m py_compile app.py
        python -m py_compile modules/*.py
    
    - name: Test imports
      run: |
        python -c "import app; import modules.network_discovery; import modules.ssh_operations; import modules.config_generator; import modules.status_manager"
